name: Core CI

on:
  pull_request:
    branches:
      - 'releases/**'
      - 'hotfix/**'

  push:
    branches:
      - 'releases/**'
      - 'master'

jobs:
  Build:
    env:
      dotnet_version: "3.1.101"

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Fetch tags for GitVersion
      run: git fetch --tags --unshallow

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.3
      with:
        versionSpec: '5.3.x'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.3
      with:
        additionalArguments: -diag
